stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

docker-build:
  stage: build
  image: maven:3.8.1-openjdk-17
  services:
    - docker:20.10.16-dind
  script:
    - mvn clean install
    - docker-compose build --no-cache
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

test:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker-compose up -d
    - docker ps | grep 'jobnestbackend-container'
    - docker ps | grep 'jobnestfrontend-container'
    - docker ps | grep 'postgres-container'
    - curl http://localhost:8080/ # checks if the backend is running
    - curl http://localhost:3000/ # checks if the frontend is running
  only:
    - main

deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Déploiement de l'application"
    - docker-compose up -d
  only:
    - main
