stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build_backend:
  stage: build
  image: maven:3.8.6-openjdk-17
  script:
    - cd JobNest-backend
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - JobNest-backend/target/*.jar  # Store the jar file for the next stages

docker-build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker-compose build
  only:
    - main

test:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker ps | grep 'jobnestbackend-container'
    - docker ps | grep 'jobnestfrontend-container'
    - docker ps | grep 'postgres-container'
    - curl http://localhost:8080/ # checks if the backend is running
    - curl http://localhost:3000/ # checks if the frontend is running
  only:
    - main

deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Déploiement de l'application"
    - docker-compose up -d
  only:
    - main
