services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./JobNest-backend
    container_name: jobnestbackend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./JobNest-frontend
    container_name: jobnestfrontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

